### ISSUE TITLE
ch04/pigs/sent_counts.pig

### ISSUE THREAD

**Issue by joechong88** [rjurney/Agile_Data_Code#13]
I finally managed to get AWS S3, EMR and DotCloud setup. I'm on pg 77 in the book to run the sent_counts.pig, albeit AWS style. 

The following lines are what I've changed to:
/\* Set Home Directory - where we install software Pig */
%default HOME '/home/hadoop/.versions/pig-0.11.1.1'

REGISTER $HOME/build/ivy/lib/Pig/avro-1.7.4.jar
REGISTER $HOME/build/ivy/lib/Pig/json-simple-1.1.jar
REGISTER $HOME/contrib/piggybank/java/piggybank.jar

When I ssh into the EMR site, i can't find avro or json-simple. Is there a separate location for them, or if not, how do I build from scratch, or upload them into AWS?

**Comment by joechong88** [comment]
Thought of a way, which is to load the afro-1.7.4.jar and json-simple-1.1.jar into s3://, and during the EMR process, add steps to load the custom JARs. Is that the right approach? Meanwhile, as I'm using Amazon's version of pig which is 0.11.1, I should reference the existing piggybank.jar in aws' /home/hadoop location.

Thoughts?

**Comment by rjurney** [comment]
You'll need to either scp the jars up to the EMR master, or copy them to HDFS/S3.
