### ISSUE TITLE
ch09/classify.py source code is missing

### ISSUE THREAD

**Issue by joechong88** [rjurney/Agile_Data_Code#15]
Can you please help upload? Thanks.

**Comment by rjurney** [comment]
That functionality was encompassed by https://github.com/rjurney/Agile_Data_Code/blob/master/ch09/web/index.py

if it still says classify.py in the book, I'll need to fix that in the next edition, sorry!

**Comment by joechong88** [comment]
OK, got it. Thanks. Will close this issue then.
