### ISSUE TITLE
error (imaplib.error) occurs when try to run gmail.py 

### ISSUE THREAD

**Issue by JamesGetexp** [rjurney/Agile_Data_Code#28]
Follow instruction in chapter 3 to run $ ./gmail.py -m automatic -u xxxxxxx@gmail.com -p 'xxxxxx' -s ./email.avro.schema -f '[Gmail]/All Mail' -o /tmp/my_inbox_directory 2>&1 &

To get data from gmail, here is the error:

$ Timeout exception occurred!
Warning: /tmp/my_inbox_directory already exists:
Warning: /tmp/my_inbox_directorytmp already exists:
Traceback (most recent call last):
  File "./gmail.py", line 104, in <module>
    main()
  File "./gmail.py", line 85, in main
    status, count = slurper.init_folder(imap_folder)
  File "/home/james/training/ADS/gmail/gmail_slurper.py", line 68, in init_folder
    status, count = self.imap.select(folder)
  File "/usr/lib/python2.7/imaplib.py", line 649, in select
    typ, dat = self._simple_command(name, mailbox)
  File "/usr/lib/python2.7/imaplib.py", line 1070, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python2.7/imaplib.py", line 825, in _command
    ', '.join(Commands[name])))
imaplib.error: command SELECT illegal in state NONAUTH, only allowed in states AUTH, SELECTED

any idea?

**Comment by JamesGetexp** [comment]
I solved this issue. It was a connection issue with gmail. 

However, in chap 03, gmail_slurper.py  - I believe there is an issue with the code, since except was passed without given any error output. (I have to comment it out in order to figure out there was an issue with my connection to gmail. 

At: line 37 and 38, except: and pass should be comment out, because any s
    try:
      self.imap = imaplib.IMAP4_SSL('imap.gmail.com', 993)
      self.imap.login(username, password)
      self.imap.is_readonly = True
  #  except:
  #    pass

**Comment by harishvc** [comment]
@JamesGetexp I have the same error message (imaplib.error ...). How did you solve?

**Comment by alouisos** [comment]
Mind also that folder  '[Gmail]/All Mail' is valid for gmails that have basic language in English.

Before running the gmail.py script change the basic language of your gmail to english on settings or the script will not run (or try to set the folder to the equivalent in your language).

**Comment by AndrewMLewis** [comment]
I found that even if it already said the language was English(United States) I needed to go in and set it explicitly.  If you are carrying the default, even if it looks correct, gmail.py still blows up.

**Comment by ldshou** [comment]
@JamesGetexp How did you solve the connection problem? I got exactly the same error as yours.

**Comment by davidfisherenterprises** [comment]
Hi all, I know it's been awhile since anyone posted/updated on the NOAUTH problem.  I spent the better part of 4 hours figuring this out today (I was having the same problem).  You can view [[what you need to do here: http://www.davidlfisher.org/index.php/2020/02/12/agile-data-science-updated-code-and-setup/

**Comment by rjurney** [comment]
As the author, I strongly advise you against using this code or reading this book. Check out Agile Data Science 2.0, the new version.
