### ISSUE TITLE
gmail.py - Handling of Unicode

### ISSUE THREAD

**Issue by joechong88** [rjurney/Agile_Data_Code#8]
I'm still getting the following error even though the slurp function already has handling of unicode error. The following is the error I'm encountering, which stops the read of my mailbox.  

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

Is there an extra handling required at the slurp function?

**Comment by rjurney** [comment]
There is a fix for this, it requires writing duplicate avro files, one to keep and another to catch write errors. I will implement this solution this weekend.

**Comment by joechong88** [comment]
I'm testing out the solution that I put in now. Once confirmed working, I'll put in a  pull request. Stay tuned.

**Comment by joechong88** [comment]
We can close this issue then, given the latest has already been committed.
